# Auto-loaded for local development (docker compose up)
# Skipped in production when using: docker compose -f docker-compose.yml -f docker-compose.prod.yml up
services:
  wikibase:
    ports:
      - "8080:80"

  wdqs:
    ports:
      - "9999:9999"

  wdqs-frontend:
    ports:
      - "8081:80"
    environment:
      WDQS_PUBLIC_URL: "http://localhost:8081/proxy/sparql"
      WIKIBASE_PUBLIC_URL: "http://localhost:8080/w/api.php"
