# This file is provided by the wikibase/wdqs-frontend docker image.
server {
    listen       80;
    server_name  localhost;

    location /proxy/sparql {
        proxy_pass http://wdqs:9999/bigdata/namespace/wdq/sparql;
    }

    location /node_modules/jquery.uls/i18n/ {
        alias /usr/share/nginx/html/i18n/;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
